output_path: ../DARLA_output

module: "dae" #choose "dae" or "beta_vae"

save_n_epochs: 100
data:
  loaders:
    batch_size: 4
    num_workers: 4
  files:
    base: ./shared/
    train: train.txt

  max_samples: -1

  shape: [3, 480, 640]
  transforms:
    - name: hflip
      ignore: true
      p: 0.5
    - name: resize
      ignore: true
      new_size: [480, 640]
    - name: crop
      ignore: true
      height: 250
      width: 250
    - name: colorjitter
      ignore: false
      brightness: 1
      contrast: 0.5
      saturation: 0.5
      hue: 0.5

num_epochs: 10000

latent_dim: 32

betavae_lr: 0.0001
beta: 1

dae_lr: 0.001

comet:
  api_key: "None"
  project_name: "None"
  workspace: "None"