
data:
  loaders:
    batch_size: 4
    num_workers: 4
  
  files:
    base: /home/mila/t/tengmeli/challenge-aido_LF-baseline-RL-sim-pytorch/DARLA/
    train: train.txt
    val: val.txt

  max_samples: -1

  transforms:
    - name: hflip
      ignore: true
      p: 0.5
    - name: resize
      ignore: false
      new_size: 512
    - name: crop
      ignore: false
      height: 500
      width: 500
    - name: colorjitter
      ignore: false
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0.5
      
    - name: resize 
      ignore: false
      new_size: 512

num_epochs: 100
lr: 1e-4

