output_path: /miniscratch/tengmeli/DARLA
data:

  loaders:
    batch_size: 4
    num_workers: 4
  
  files:
    base: /home/mila/t/tengmeli/challenge-aido_LF-baseline-RL-sim-pytorch/DARLA/shared/
    train: sample_train.txt #train.txt
    val: #val.txt

  max_samples: -1
  
  n_obs: 3 
  transforms:
    - name: hflip
      ignore: true
      p: 0.5
    - name: resize
      ignore: false
      new_size: 256
    - name: crop
      ignore: false
      height: 250
      width: 250
    - name: colorjitter
      ignore: false
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0.5
      
    - name: resize 
      ignore: false
      new_size: 256

num_epochs: 100

betavae_lr: 1e-4
beta: 4

dae_lr: 1e-3

save_iter: 20